### This is the Torch introduction video 

In [2]:
import torch
t1 = torch.tensor(4.)

In [3]:
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [9]:
# vector
t2 = torch.tensor([1,2.,3,4]) #if any one value become higer order all values becomes at higher order datatype
# t2 = torch.tensor([1,2,3,4]) 
t2

tensor([1, 2, 3, 4])

In [14]:
#2d tensor  
t3 = torch.tensor([[1,2],
       [3,4],
       [5,6]])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [24]:
# 3D tensor
t4 = torch.tensor([[[1,2],[3,4],[5,6]]
                   ,[[9,8],[7,6],[2,3]]])
t4

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[9, 8],
         [7, 6],
         [2, 3]]])

In [22]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)



torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 3, 2])


### Tensor Operations 

In [33]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)

x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [39]:
y = x*w+b
y

tensor(17., grad_fn=<AddBackward0>)

In [40]:
# Compute derivatives
y.backward()

In [43]:
# contains the gradients int he required_grads=True
print(w.grad)

tensor(3.)


In [44]:
print("dy/dx : ", x.grad)
print("dy/dw : ", w.grad)
print("dy/db : ", b.grad)


dy/dx :  None
dy/dw :  tensor(3.)
dy/db :  tensor(1.)


### Tensor Function

In [63]:
# Creating the tensor and full fill with a single value 
t6 = torch.full((3,3),10)
t6

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

In [60]:
t3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [64]:
t = torch.full((3,3),12)
t

tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])

In [68]:
t7 = torch.cat((t6,t))
t7

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])

In [69]:
t8 = torch.sin(t7)
t8

tensor([[-0.5440, -0.5440, -0.5440],
        [-0.5440, -0.5440, -0.5440],
        [-0.5440, -0.5440, -0.5440],
        [-0.5366, -0.5366, -0.5366],
        [-0.5366, -0.5366, -0.5366],
        [-0.5366, -0.5366, -0.5366]])

In [79]:
t9 = t8.reshape(3,3,2)
t9

tensor([[[-0.5440, -0.5440],
         [-0.5440, -0.5440],
         [-0.5440, -0.5440]],

        [[-0.5440, -0.5440],
         [-0.5440, -0.5366],
         [-0.5366, -0.5366]],

        [[-0.5366, -0.5366],
         [-0.5366, -0.5366],
         [-0.5366, -0.5366]]])

### Interportability of Numpy


In [ ]:
import numpy as np 


In [83]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [88]:
m = x.reshape(3,2)
m

array([[0, 1],
       [2, 3],
       [4, 5]])

In [90]:
y = torch.from_numpy(m)
y

tensor([[0, 1],
        [2, 3],
        [4, 5]])